import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "None"
opacity = 0.8
startup_mode = "Maximized"

[font]
normal = { family = "Fira Code", style = "Regular" }
size = 12

[cursor]
unfocused_hollow = false
